config/routes.rb
Rails.application.routes.draw do
  resources :articles

  resources :users

  namespace :user do
  get 'session/new'
  get 'login', to: 'session#new', as: :login
  delete 'logout', to: 'session#destroy', as: :logout
  post 'sessions', to: 'session#create', as: :sessions
  end

  namespace :user do
  get 'session/create'
  end

  namespace :user do
  get 'session/destroy'
  end

  get 'main/index'
  root to: 'main#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  include PolymorphicCommonInstance
  acts_as_common :resource
end

app/models/resource.rb
class Resource < ActiveRecord::Base
  include PolymorphicExtension
  belongs_to :instance, polymorphic: true
  belongs_to :user
  validates_presence_of :user

  set_accessable_attributes :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :resources
  validates :account, presence: true, uniqueness: true
  validates_presence_of :password_confirmation, :on => :create

  def articles
    Article.joins("JOIN resources ON articles.id = resources.instance_id 
        AND resources.instance_type = 'Article' ").where('resources.user_id = ?', id).order('created_at DESC')
  end
end

app/models/user/session.rb
class User::Session
  include FakeActiveRecord::ForForm
  has_fake_attr :account, :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include I18nExtension
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protected
    def current_user
      @current_user ||= session[:user_id] && User.find(session[:user_id])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_layout
  layout "common"
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_ = current_user
    
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article}
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article}
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to root_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end
    def set_layout

    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content).tap{ |p|
        [:title, :content].each { |e|
          p[e].empty? ? p[e]=tp("no_#{e}", :article) : nil
        }
      }
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @articles = current_user && current_user.articles
  end
end

app/controllers/user/session_controller.rb
class User::SessionController < ApplicationController
  def new
    @session = User::Session.new
  end

  def create
    session_params = params[:user_session]
    @user = User.find_by(account: session_params[:account])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      @session = User::Session.new
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:account, :nickname, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include I18nExtension
  def label_tag_t(name = nil, content_or_options = nil, options = nil, &block)
    label_tag(t(".#{name.to_s}"), content_or_options, options, &block)
  end

  def simple_format_wsp(text, html_options = {}, options = {})
    res = ""
    text = h(text)
    text.each_line do |line|
      m = line.match(/(^ +)([^ ]*)/)
      l = m ? m[1].length : 0
      line = "&nbsp;"*l + line[l..-1]
      res<<line
    end
    simple_format(res, html_options, options)
  end

  def truncate_wch(text, options = {}, &block)
    return unless text
    length = options.fetch(:length, 30)
    index = l =0
    text.each_char do |ch|
      if ch.ascii_only?
        l+=0.9
      else
        l+=2
      end
      index+=1
      break if l>=length
    end
    truncate(text, length: index)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/user/session_helper.rb
module User::SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div id="article-area">
  <%= form_for(@article) do |f| %>
    <div class='submit'>
      <%= f.submit nil, class: "btn" %>
      <%= link_to Article.exists?(@article) ? @article : root_url do  %>
        <button id="cancel" class="btn">取消</button>
      <% end %>
    </div>
    <div id="article-title">
      <%= f.text_field :title, placeholder: tp('input_title', :article) %>
    </div>
    <div id="article-time">
      <%= l Time.now %>
    </div>
    <div id="article-content">
      <%= f.text_area :content, placeholder: tp('input_content', :article) %>
    </div>
    <% if Article.exists? @article %>
      <div id="delete-article">
        <%= link_to article_path(@article), method: :delete, data:{ confirm: 'Sure?'} do  %>
          <%= fa_icon 'times 2x' %>
        <% end %> 
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/_index.html.erb
<% @articles.each do |article| %>
  <div class="resource-row">
    <%= link_to truncate_wch(article.title, length: 36), article %><span class="create-time"><%= l article.created_at %></span>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div id="article-area">
  <div id="article-title">
    <%= @article.title %>
  </div>
  <div id="article-time">
    <%= l @article.created_at %>
    <div id="article-function">
      <%= link_to edit_article_path(@article) do %>
        <%= fa_icon "pencil", id: 'article-edit'%>
      <% end %>
    </div>
  </div>
  <div id="article-content">
    <%= simple_format_wsp @article.content  %>
  </div>
</div>
<!-- 
<%# link_to 'Edit', edit_article_path(@article) %> |
<%#link_to 'Back', articles_path %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
  <title>Avalon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body cont="<%= params[:controller] %>">
<%= yield %>
<div></div>
</body>
</html>

app/views/layouts/common.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
  <title>Avalon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body cont="<%= params[:controller] %>">
<nocont>
    <div id="nav">
      <div id="nav-title"><%= link_to 'Avalon', root_path %> | <small> <%= current_user.nickname %>'s blog</small>  </div>
    </div>
</nocont>
<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<nocont>
<div id="top-area">

    <% if current_user %>
<!--     <div id="nav">
      <div class="nav-right">
        <%= link_to tf('logout'), user_logout_path, method: :delete %>
      </div>
    </div> -->
    <div id='site-title'>Avalon</div>
    <div id="title-user">-<%= current_user.nickname %>'s Blog-</div>
    <% else %>
      <div id="title-user">-<%= link_to tf('login'), user_login_path %>-</div>
    <% end %>

  </div>
</div>
</nocont>

<% if current_user %>
<div id='new-article'>
  <%= link_to new_article_path do %>
  <button class='btn'><%= tp('new', 'article') %></button>
  <% end %>
</div>
<div id="resource-show">
  <%= render 'articles/index' %>
</div>
<% else %>



<% end %>

app/views/user/session/create.html.erb
<h1>User::Session#create</h1>
<p>Find me in app/views/user/session/create.html.erb</p>

app/views/user/session/destroy.html.erb
<h1>User::Session#destroy</h1>
<p>Find me in app/views/user/session/destroy.html.erb</p>

app/views/user/session/new.html.erb
<%= form_for @session do |f|%>
  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <%= f.submit nil, :id => "submit", :name => "submit", :class => "form_submit", data: { disable_with: tf(:processing) } %>
<% end -%>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account %><br>
    <%= f.text_field :account %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>
      <th>Nickname</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.account %></td>
        <td><%= user.nickname %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @user.account %>
</p>

<p>
  <strong>Nickname:</strong>
  <%= @user.nickname %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>